# Config file for automatic testing at travis-ci.org
language: python
python:
    #- "2.7"
    #- "3.2"
    - "3.3"
    - "3.4"
    - "3.5-dev"

env:
    global:
        - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so

# command to install dependencies
install:
    - pip install -r coverage_requirements.txt

# command to run tests
script:
    - ./.travis-script.sh

after_success:
    codecov
