# Config file for automatic testing at travis-ci.org
language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"

env:
    global:
        - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so

# command to install dependencies
install:
    - pip install -r coverage_requirements.txt

# command to run tests
script:
    - ./.travis-script.sh
    - py.test -l -vv --no-cov-on-fail --cov=docmanager --cov-report=term-missing

after_success:
    codecov
