# Config file for automatic testing at travis-ci.org
language: python
python:
    #- "2.7"
    #- "3.2"
    - "3.3"
    - "3.4"

env:
    global:
        - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so

# command to install dependencies
install:
    - pip install -r coverage_requirements.txt

# command to run tests
script:
    - coverage run setup.py test
    - python3 setup.py install
    
    # test with real SUSE documentation
    - git remote add upstream git://github.com/openSUSE/docmanager.git
    - git fetch upstream test-data
    - git checkout test-data
    - cd doc-sle
    - docmanager init *
    - cd ../doc-sleha
    - docmanager init *
    - cd ../doc-cloud
    - docmanager init *

after_success:
    codecov
